{
 "title": "Test-Cluster-PD",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(pd_cluster_status, instance)"
   },
   {
    "name": "store",
    "label": "store",
    "query": "label_values(pd_scheduler_store_status, store)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "PD role",
     "type": "singlestat",
     "description": "It indicates whether the current PD is the leader or a follower.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "delta(pd_tso_events{type=\"save\",instance=\"$instance\"}[1m]) > bool 0"
      }
     ]
    },
    {
     "title": "Storage capacity",
     "type": "singlestat",
     "description": "The total capacity size of the cluster",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",type=\"storage_capacity\"})"
      }
     ]
    },
    {
     "title": "Current storage size",
     "type": "singlestat",
     "description": "The current storage size of the cluster",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",type=\"storage_size\"})"
      }
     ]
    },
    {
     "title": "Current storage used",
     "type": "singlestat",
     "description": "The current storage size and used ratio of the cluster",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",type=\"storage_size\"}) / sum(pd_cluster_status{instance=\"$instance\",type=\"storage_capacity\"})"
      }
     ]
    },
    {
     "title": "Normal stores",
     "type": "singlestat",
     "description": "The count of healthy stores",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",  type=\"store_up_count\"})"
      }
     ]
    },
    {
     "title": "Number of Regions",
     "type": "singlestat",
     "description": "The total number of Regions without replicas",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",type=\"leader_count\"})"
      }
     ]
    },
    {
     "title": "PD scheduler config",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "targets": [
      { "expr": "pd_config_status", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "Region label isolation level",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 6, "y": 7 },
     "targets": [
      {
       "expr": "pd_regions_label_level{instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Label distribution",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 11, "y": 7 },
     "targets": [
      { "expr": "pd_cluster_placement_status", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Abnormal stores",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", type=\"store_disconnected_count\"})",
       "legendFormat": "Disconnect Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", type=\"store_unhealth_count\"})",
       "legendFormat": "Unhealth Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", type=\"store_low_space_count\"})",
       "legendFormat": "LowSpace Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", type=\"store_down_count\"})",
       "legendFormat": "Down Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", type=\"store_offline_count\"})",
       "legendFormat": "Offline Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", type=\"store_tombstone_count\"})",
       "legendFormat": "Tombstone Stores"
      }
     ]
    },
    {
     "title": "pd_cluster_metadata",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "pd_cluster_metadata{instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current peer count",
     "type": "graph",
     "description": "The current peer count of the cluster",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",  type=\"region_count\"})",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Region health",
     "type": "graph",
     "description": "It records the unusual Regions' count which may include pending peers, down peers, extra peers, offline peers, missing peers or learner peers",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_regions_status{instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Schedule operator create",
     "type": "graph",
     "description": "The number of different operators that are newly created",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"create\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator check",
     "type": "graph",
     "description": "The number of different operators that have been checked. It mainly checks if the current step is finished; if yes, it returns the next step to be executed.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"check\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator finish",
     "type": "graph",
     "description": "The number of different operators that are finished",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"finish\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator timeout",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"timeout\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator replaced or canceled",
     "type": "graph",
     "description": "The number of different operators that are replaced or canceled",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"cancel\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"replace\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operators count by state",
     "type": "graph",
     "description": "The number of operators in different status",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\"}[1m])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "99% Operator finish duration",
     "type": "graph",
     "description": "The time consumed when the operator is finished in .99",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_finish_operators_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "50% Operator finish duration",
     "type": "graph",
     "description": "The time consumed when the operator is finished in .50",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(pd_schedule_finish_operators_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99% Operator step finish duration",
     "type": "graph",
     "description": "The time consumed when the operator step is finished in .99",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_finish_operator_steps_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "50% Operator step finish duration",
     "type": "graph",
     "description": "The time consumed when the operator step is finished in .50",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(pd_schedule_finish_operator_steps_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics - balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Store capacity",
     "type": "graph",
     "description": "The capacity size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"store_capacity\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store available",
     "type": "graph",
     "description": "The available capacity size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "{store=~\"$store\", instance=\"$instance\",  type=\"store_available\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store used",
     "type": "graph",
     "description": "The used capacity size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"store_used\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store available ratio",
     "type": "graph",
     "description": "It is equal to Store available capacity size over Store capacity size for each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"store_available\"}) by (address, store) / sum(pd_scheduler_store_status{instance=\"$instance\",  type=\"store_capacity\"}) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Size amplification",
     "type": "graph",
     "description": "The size amplification, which is equal to Store Region size over Store used capacity size, of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"region_size\"}) by (address, store) / sum(pd_scheduler_store_status{instance=\"$instance\",  type=\"store_used\"}) by (address, store) * 2^20",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store Region score",
     "type": "graph",
     "description": "The Region score of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"region_score\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader score",
     "type": "graph",
     "description": "The leader score of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"leader_score\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store Region size",
     "type": "graph",
     "description": "The total Region size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"region_size\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader size",
     "type": "graph",
     "description": " \tThe total leader size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"leader_size\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store Region count",
     "type": "graph",
     "description": "The Region count of each TiKV instance \t",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"region_count\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader count",
     "type": "graph",
     "description": "The leader count of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", instance=\"$instance\",  type=\"leader_count\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics - hotspot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hot write Region's leader distribution",
     "type": "graph",
     "description": "The total number of leader Regions under hot write on each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{store=~\"$store\", instance=\"$instance\", type=\"hot_write_region_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot write Region's peer distribution",
     "type": "graph",
     "description": "The total number of Regions which are not leader under hot write on each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{store=~\"$store\", instance=\"$instance\", type=\"hot_write_region_as_peer\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot write Region's leader written bytes",
     "type": "graph",
     "description": "The total bytes of hot write on leader Regions for each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{store=~\"$store\", instance=\"$instance\", type=\"total_written_bytes_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot Region's peer written bytes",
     "type": "graph",
     "description": "The total bytes of hot write on Regions which are not leader for each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{store=~\"$store\", instance=\"$instance\", type=\"total_written_bytes_as_peer\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot read Region's leader distribution",
     "type": "graph",
     "description": "The total number of leader Regions under hot read on each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{store=~\"$store\", instance=\"$instance\", type=\"hot_read_region_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot read Region's leader read bytes",
     "type": "graph",
     "description": "The total bytes of hot read on leader Regions for each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{store=~\"$store\", instance=\"$instance\", type=\"total_read_bytes_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store write rate bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", type=\"store_write_rate_bytes\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store read rate bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", type=\"store_read_rate_bytes\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store write rate keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", type=\"store_write_rate_keys\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store read rate keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{store=~\"$store\", type=\"store_read_rate_keys\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler is running",
     "type": "graph",
     "description": "The current running schedulers",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_status{type=\"allow\",instance=\"$instance\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Balance leader movement",
     "type": "graph",
     "description": "The leader movement details among TiKV instances",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "- sum(delta(pd_scheduler_balance_leader{store=~\"$store\", address=~\".*out\",instance=\"$instance\", type=\"move-leader\"}[30s])) by (address, store)",
       "legendFormat": "store-{{store}}"
      },
      {
       "expr": "sum(delta(pd_scheduler_balance_leader{store=~\"$store\", address=~\".*in\",instance=\"$instance\", type=\"move-leader\"}[30s])) by (address, store)",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance Region movement",
     "type": "graph",
     "description": "The Region movement details among TiKV instances",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "-sum(delta(pd_scheduler_balance_region{store=~\"$store\", address=~\".*out\",instance=\"$instance\", type=\"move-peer\"}[1m])) by (address, store)",
       "legendFormat": "store-{{store}}"
      },
      {
       "expr": "sum(delta(pd_scheduler_balance_region{store=~\"$store\", address=~\".*in\",instance=\"$instance\", type=\"move-peer\"}[1m])) by (address, store)",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance leader event",
     "type": "graph",
     "description": "The count of balance leader events",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_balance_leader{store=~\"$store\", instance=\"$instance\", type!=\"move-leader\"}[30s])) by (type, address, store)",
       "legendFormat": "{{type}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance Region event",
     "type": "graph",
     "description": "The count of balance Region events",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_balance_region{store=~\"$store\", instance=\"$instance\", type!=\"move-peer\"}[30s])) by (type, address, store)",
       "legendFormat": "{{type}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance leader scheduler",
     "type": "graph",
     "description": "The inner status of balance leader scheduler",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_event_count{instance=\"$instance\", type=\"balance-leader-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Balance Region scheduler",
     "type": "graph",
     "description": "The inner status of balance Region scheduler",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_event_count{instance=\"$instance\", type=\"balance-region-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Replica checker",
     "type": "graph",
     "description": "The replica checker's status",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_checker_event_count{instance=\"$instance\", type=\"replica_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Region merge checker",
     "type": "graph",
     "description": "The merge checker's status",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_checker_event_count{instance=\"$instance\", type=\"merge_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filter target",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_filter{store=~\"$store\", action=\"filter-target\"}[1m])) by (store, type, scope)",
       "legendFormat": "{{scope}}-store-{{store}}-{{type}}"
      }
     ]
    },
    {
     "title": "Filter source",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_filter{store=~\"$store\", action=\"filter-source\"}[1m])) by (store, type, scope)",
       "legendFormat": "{{scope}}-store-{{store}}-{{type}}"
      }
     ]
    },
    {
     "title": "Balance Direction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_balance_direction{instance=\"$instance\"}[1m])) by (type, source, target)",
       "legendFormat": "{{source}}-{{target}}-{{type}}"
      }
     ]
    },
    {
     "title": "Store Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "pd_schedule_store_limit{store=~\"$store\", type=\"available\"}",
       "legendFormat": "{{store}}-avaliable"
      },
      {
       "expr": "pd_schedule_store_limit{store=~\"$store\", type=\"take\"}",
       "legendFormat": "{{store}}-take"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Completed commands rate",
     "type": "graph",
     "description": "The rate of completing each kind of gRPC commands",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handling_seconds_count{instance=\"$instance\"}[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99% Completed commands duration",
     "type": "graph",
     "description": "The time consumed of completing each kind of gRPC commands in .99",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{instance=\"$instance\"}[5m])) by (grpc_method, le))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handle transactions rate",
     "type": "graph",
     "description": "The rate of handling etcd transactions",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 162 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_txn_handle_txns_duration_seconds_count[5m])) by (instance, result)",
       "legendFormat": "{{instance}} : {{result}}"
      }
     ]
    },
    {
     "title": "99% Handle transactions duration",
     "type": "graph",
     "description": "The time consumed of handling etcd transactions in .99",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_txn_handle_txns_duration_seconds_bucket[5m])) by (instance, result, le))",
       "legendFormat": "{{instance}} {{result}}"
      }
     ]
    },
    {
     "title": "99% WAL fsync duration",
     "type": "graph",
     "description": "The time consumed of writing WAL into the persistent storage in .99",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "99% Peer round trip time seconds",
     "type": "graph",
     "description": "The latency of the network in .99",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket[5m])) by (instance, To, le))",
       "legendFormat": "{{instance}} - {{To}}"
      }
     ]
    },
    {
     "title": "etcd disk wal fsync rate",
     "type": "graph",
     "description": "The rate of writing WAL into the persistent storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "delta(etcd_disk_wal_fsync_duration_seconds_count[1m])",
       "legendFormat": "{{instance}} etch disk wal fsync rate"
      }
     ]
    },
    {
     "title": "Raft term",
     "type": "graph",
     "description": "The current term of Raft",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 186 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_server_etcd_state{type=\"term\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Raft committed index",
     "type": "graph",
     "description": "The last committed index of Raft",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 186 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_server_etcd_state{type=\"committedIndex\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Raft applied index",
     "type": "graph",
     "description": " \tThe last applied index of Raft",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 186 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_server_etcd_state{type=\"appliedIndex\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TiDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handle requests count",
     "type": "graph",
     "description": "The count of TiDB requests",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_request_handle_requests_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Handle requests duration",
     "type": "graph",
     "description": "The time consumed of handling TiDB requests",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.98, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket[30s])) by (type, le))",
       "legendFormat": "{{type}} 98th percentile"
      },
      {
       "expr": "avg(rate(pd_client_request_handle_requests_duration_seconds_sum[30s])) by (type) /  avg(rate(pd_client_request_handle_requests_duration_seconds_count[30s])) by (type)",
       "legendFormat": "{{type}} average"
      }
     ]
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% Region heartbeat latency",
     "type": "graph",
     "description": "The heartbeat latency of each TiKV instance in .99",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "round(histogram_quantile(0.99, sum(rate(pd_scheduler_region_heartbeat_latency_seconds_bucket{store=~\"$store\"}[5m])) by (address, store, le)), 1000)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region schedule push",
     "type": "graph",
     "description": "The count of the corresponding schedule commands which PD sends to each TiKV instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_region_heartbeat{store=~\"$store\", type=\"push\",instance=\"$instance\"}[5m])*60) by (address, store, status)",
       "legendFormat": "{{address}}-{{status}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report",
     "type": "graph",
     "description": "The count of the heartbeats which each TiKV instance reports to PD",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{store=~\"$store\", instance=\"$instance\", type=\"report\", status=\"ok\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report active",
     "type": "graph",
     "description": "The count of the heartbeats with the ok status",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{store=~\"$store\", instance=\"$instance\", type=\"report\", status=\"bind\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report error",
     "type": "graph",
     "description": "The count of the heartbeats with the error status",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{store=~\"$store\", instance=\"$instance\", type=\"report\", status=\"err\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Region storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syncer index",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 213 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_region_syncer_status{type=\"sync_index\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "History last index",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 213 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_region_syncer_status{type=\"last_index\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}